#!/usr/bin/env node
/**
 * Keeps `src/version.ts` in step with package.json's version.
 *
 * Wired to npm's `version` lifecycle, so `npm version <x>` rewrites the
 * constant as part of the bump instead of leaving it to be remembered.
 * It had drifted a long way before this existed - package.json was on
 * 26.6.10 while the constant still said 25.7.5 - because every release
 * commit touched package.json alone.
 *
 * `__tests__/versionInSync.test.ts` fails the build if the two ever
 * disagree, which covers the other way in: editing package.json by hand.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'src', 'version.ts');

const { version } = JSON.parse(
  readFileSync(join(root, 'package.json'), 'utf8')
);

const contents = `// Generated by scripts/sync-version.mjs on \`npm version\`.
// Edit package.json's version instead of this file.
export const ETHORA_CHAT_COMPONENT_VERSION = '${version}';
`;

const previous = readFileSync(target, 'utf8');
if (previous === contents) {
  console.log(`sync-version: src/version.ts already at ${version}`);
  process.exit(0);
}

writeFileSync(target, contents);
console.log(`sync-version: src/version.ts -> ${version}`);

// When `npm version` is creating its own commit, files the `version`
// script changed only make it in if they're staged. Harmless when the
// bump is run with --no-git-tag-version (it just leaves the file
// staged) and when there's no git repo at all.
try {
  execFileSync('git', ['add', target], { cwd: root, stdio: 'ignore' });
} catch {
  // not a git checkout, or git unavailable - the write above is what matters
}
